update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,6 +17,11 @@ jobs:
         run: |
           zip -r MagickTes.zip .
 
+      - name: Delete the existing tag (if exists)
+        run: |
+          git tag -d 1.0.0.0 || echo "Tag not found locally"
+          git push origin --delete 1.0.0.0 || echo "Tag not found remotely"
+
       - name: Create a new tag
         id: create_tag
         run: |
@@ -25,12 +30,10 @@ jobs:
           git config user.email "kylefcapistrano@gmail.com"
           git tag $TAG_NAME  # Create the tag
           git push origin $TAG_NAME  # Push the tag to the repository
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate
 
       - name: Upload ZIP to Release
         uses: softprops/action-gh-release@v1
         with:
-          files: MagickTes.zip  # Upload the generated zip file
+          files: MagickTes.zip
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
